name: Webwhats
description: A WhatsappWeb wrapper to be used directly from mobile or tablets.

version: 1.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.3+7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 19

flutter:
  uses-material-design: true
